name: Notify Main Site

on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger main site update
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MAIN_SITE_PAT }}" \
          https://api.github.com/repos/${{ vars.MAIN_SITE_REPO }}/dispatches \
          -d '{"event_type":"wiki-updated"}'
      
